version: '3'
services:
  api:
    build:
      context: .
      dockerfile:  ./Dockerfile
    command: bash -c "bundle exec rake db:migrate && foreman start"
    links:
      - database:database
    environment:
      - DATABASE_PASSWORD
      - DATABASE_USER=postgres
      - DOCKERIZED=true
      - DEVISE_JWT_SECRET_KEY
    depends_on:
      - database
    restart: always
  ui:
    build: https://github.com/Kristiyan96/infbase-frontend.git
    links:
      - api:api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/api-endpoint.conf
    ports:
      - "3000:80"
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "inf_base_development"
      POSTGRES_USER: "infbase"
    restart: always